INSERT INTO CATEGORIA (NOME) VALUES ('Lazer'); 
INSERT INTO CATEGORIA (NOME) VALUES ('alimentação');
INSERT INTO CATEGORIA (NOME) VALUES ('Supermercado');
INSERT INTO CATEGORIA (NOME) VALUES ('Farmacia');
INSERT INTO CATEGORIA (NOME) VALUES ('Outros'); 